model: "EleutherAI/gpt-neo-1.3b"

train_path: "data/summarize_from_feedback.jsonl"
keys: ["body", "summary", "feedback"]

lr: 0.00005
train_steps: 5000
warmup_steps: 50
batch_size: 4

save_dir: "runs/predict_feedback"
log_interval: 10
