device: "cpu"
model:
  arch: "MultiHeadModel"
  context_length: 8
  d_model: 96
  num_heads: 6
train:
  batch_size: 32
  eval_interval: 100
  eval_iters: 1
  learning_rate: 3.e-4
  max_iters: 100_000
  # train_set_length: 9
wandb:
 name: "multihead_attention"
